page.get_by_role("link", name="托管业务 ").click()
    page.get_by_role("link", name="托管账户 ").click()
    page.get_by_role("link", name="托管账户回单查询").click()
    page.locator("#inputPro").click()
    page.locator("#inputPro").fill("简州空港")
    page.locator("#inputPro").press("Enter")
    page.locator("#ulPro").click()
    page.get_by_role("listitem").filter(has_text="账户信息： 8111201012500701674").locator("span").click()
    page.get_by_role("checkbox", name="8111201012500701674").check()
    page.get_by_text("-重庆国际信托股份有限公司").click()
    page.get_by_role("listitem").filter(has_text="账户信息： 8111201012500701674").locator("span").click()
    page.locator("input[name=\"hisDay\"]").check()
    page.locator("input[name=\"startDate\"]").click()
    page.get_by_role("cell", name="").click()
    page.get_by_role("cell", name="1", exact=True).first.click()
    page.locator("input[name=\"endDate\"]").click()
    page.get_by_role("cell", name="4").first.click()
    page.get_by_role("button", name="批量下载").click()
    page.get_by_role("button", name="确认").click()